### ISSUE TITLE
https://linkvertise.com/undefined

### ISSUE THREAD

**Issue by Osdrix** [ambozz/linkvertise-bypass#1]
https://linkvertise.download/download/390492/the-pass-for-kiwi-sunset/tXFSePuHYd0Z6gmaqWX3lHsUAUdkXDKN doesn't bypass the software download

keeps reloading and the link says undefined

**Comment by ambozz** [comment]
Not an issue with this script but with the bypass.vip API this script is using.
You should try the linkvertise.com URL which lead to this linkvertise.download url.
